pod:
  template_id: "fk2s5etddm" # docker 
  gpu: "NVIDIA RTX A6000" # gpu
  gpu_count: 1
  spot: false

options:
  timeout: false
  time_limit: 3600
  terminate: true

runtime:
  cmds:
    - !CMD HF_LOGIN: ~
    - !CMD WANDB_LOGIN: ~
    - !CMD TRAIN:
      model_type: !MODEL_TYPE SmolVLA
      args:
        repo_id: "soft_manip_data"
        step: 1000
    - !CMD STOP: ~