pod:
  template_id: "yclf3vn03f" # docker 
  gpu: "NVIDIA H100 80GB HBM3"
  gpu_count: 1
  spot: false

options:
  timeout: false
  time_limit: 360000 # 100 hours
  terminate: true

runtime:
  cmds:
    - !CMD HF_LOGIN: ~
    - !CMD WANDB_LOGIN: ~
    - !CMD TRAIN:
      model_type: !MODEL_TYPE pi0_fast
      args:
        repo_id: "pick_and_place_for_train_no_tac"
        step: 10000
    - !CMD STOP: ~
    